{
    'name': 'Barca Ajustes Modulo HR',
    'version': '18.0.2.5.0',
    'depends': ['hr', 'hr_contract', 'hr_skills', 'account'],
    'data': [
        'security/res_groups.xml',
        'security/ir.model.access.csv',
        'security/hr_employee_readonly_rules.xml',
        'security/hr_contract_reference_access.xml',
        'data/cleanup_stale_views.xml',
        'data/hr_contract_reference_data.xml',
        'data/hr_accreditation_type_data.xml',
        'data/funcion_data.xml',
        'data/hr_study_level_data.xml',
        'data/hr_job_sence_classification_data.xml',
        'report/contract_report.xml',
        'report/paperformat.xml',
        'report/operador.xml',
        'report/profesional.xml',
        'report/ejecutivo.xml',
        'report/report_anexo_planta.xml',
        'report/report_actualizacion.xml',
        'report/report_pacto_he.xml',
        'views/hr_accreditation_views.xml',
        'views/it_funcion_views.xml',
        'views/hr_assigned_resource_views.xml',
        'views/hr_prevision_config_views.xml',
        'views/hr_payment_concept_views.xml',
        'views/hr_contract_view.xml',
        'views/hr_contract_reference_views.xml',
        'views/hr_tipo_obra_views.xml',
        'views/hr_city_views.xml',
        'views/hr_study_level_views.xml',
        'views/hr_job_classification_views.xml',
        'views/hr_job_family_views.xml',
        'views/hr_job_views.xml',
        'views/employee_field_usage_view.xml',
        'views/employee_views.xml',
        'views/hr_employee_additional_views.xml',
        'views/hr_employee_list_custom.xml',
        'views/resource_calendar_views.xml',
        'views/hr_employee_readonly_menu.xml',
        'views/hr_employee_readonly_views.xml',
        'views/hr_employee_function_views.xml',
        'views/hr_contract_duplicate_wizard_views.xml',
        'views/hr_contract_actualizacion_wizard_views.xml',
        'views/hr_contract_mass_print_wizard_views.xml',
        'views/hr_employee_termination_wizard_views.xml',
        'views/hr_employee_reactivation_wizard_views.xml',
        'views/hr_lugares_trabajo_views.xml',
        'views/hr_fecha_pago_views.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'zhr_ajustes/static/src/scss/hr_contract_status.scss',
        ],
    },
    'installable': True,
    'application': False,
}
