{
    'name': 'Barca Ajustes Modulo HR',
    'version': '1.0',
    'depends': ['hr', 'hr_contract', 'hr_skills', 'account', 'mail'],
    'data': [
        'security/ir.model.access.csv',
        'security/hr_mail_distribution_security.xml',
        'data/hr_mail_distribution_data.xml',
        'data/hr_contract_cron.xml',
        'report/contract_report.xml',
        'report/paperformat.xml',
        'report/operador.xml',
        'report/profesional.xml',
        'report/ejecutivo.xml',
        'report/report_anexo_planta.xml',
        'report/report_actualizacion.xml',
        'report/report_pacto_he.xml',
        'views/hr_accreditation_views.xml',
        'views/hr_assigned_resource_views.xml',
        'views/hr_prevision_config_views.xml',
        'views/hr_mail_distribution_views.xml',
        'views/hr_payment_concept_views.xml',
        'views/hr_contract_view.xml',
        'views/hr_tipo_obra_views.xml',
        'views/hr_job_family_views.xml',
        'views/hr_job_views.xml',
        'views/employee_field_usage_view.xml',
        'views/employee_views.xml',
        'views/hr_employee_additional_views.xml',
        'views/hr_employee_list_custom.xml',
        'views/resource_calendar_views.xml',
        'views/hr_contract_actualizacion_wizard_views.xml',
        'views/hr_employee_termination_wizard_views.xml',
        'views/hr_lugares_trabajo_views.xml',
        'data/hr_contract_state_labels.xml',
    ],
    'installable': True,
    'application': False,
}
